+ pin networkX to version 1.11
  - version 2.x gives an error to cosmos2 like the following:

        File "../venv/lib/python2.7/site-packages/cosmos/models/Workflow.py",
        line 570, in _run_queued_and_ready_tasks
            ready_tasks = [task for task, degree in task_queue.in_degree().items() if
            AttributeError: 'InDegreeView' object has no attribute 'items'

   - may need to address this in the future